version: "3.0"

services:
  steplemsbot:
    container_name: steplems
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "./:/config"
      - "./cache:/cache"