// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"steplems-bot/persistence/spotifyUser"
	"steplems-bot/providers"
	"steplems-bot/services/spotify"
	"steplems-bot/services/telegram"
	"steplems-bot/services/youtube"
)

// Injectors from wire.go:

func NewWireApplication() (WireApplication, error) {
	telegramBotToken, err := providers.ProvideBotToken()
	if err != nil {
		return WireApplication{}, err
	}
	telegramWebhookAddress, err := providers.ProvideBotWebhook()
	if err != nil {
		return WireApplication{}, err
	}
	botAPI, err := providers.ProvideTgBot(telegramBotToken, telegramWebhookAddress)
	if err != nil {
		return WireApplication{}, err
	}
	client := providers.ProvideYoutubeClient()
	factory := providers.LoggerFactoryProvider()
	youtubeService := youtube.NewYoutubeService(client, factory)
	databaseConnectionURL, err := providers.ProvideDatabaseConnectionURL()
	if err != nil {
		return WireApplication{}, err
	}
	db, err := providers.ProvideDatabase(databaseConnectionURL)
	if err != nil {
		return WireApplication{}, err
	}
	spotifyUserRepository := spotifyUser.NewSpotifyUserRepository(db)
	spotifyService := spotify.NewSpotifyService(spotifyUserRepository)
	authorizeSpotifyCommand := telegram.NewAuthorizeSpotifyCommand(spotifyService)
	commandMap := telegram.NewCommandMap(authorizeSpotifyCommand)
	telegramService := telegram.NewTelegramService(botAPI, youtubeService, factory, commandMap)
	wireApplication := provideWireApplication(telegramService, spotifyService)
	return wireApplication, nil
}

// wire.go:

type WireApplication struct {
	telegramService *telegram.TelegramService
	ss              *spotify.SpotifyService
}

func provideWireApplication(telegramService *telegram.TelegramService, service *spotify.SpotifyService) WireApplication {
	return WireApplication{telegramService: telegramService, ss: service}
}

func (w WireApplication) Start() {
	w.telegramService.StartBot()
}
