name: Deployment Workflow

on:
  push:
    branches: [ main ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ssh deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /root/work/steplems
            git pull origin main
            git status
            HOSTNAME="${{ secrets.REMOTE_HOST }}" docker-compose up -d --build --remove-orphans
